
/****** Object:  Table [dbo].[ROLES]    Script Date: 8/25/2019 8:11:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ROLES](
	[ROLE_ID] [int] IDENTITY NOT NULL,
	[ROLE_NAME] [varchar](200) NOT NULL,
	[ACTIVE_IND] [bit] NOT NULL,
	
	[CREATED_DT] [datetime] NULL,
	[MODIFIED_DT] [datetime] NULL,
 CONSTRAINT [ROLEID_PK] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ROLE_ID] UNIQUE NONCLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

INSERT INTO ROLES VALUES('Teacher',1, GETDATE(), GETDATE())
INSERT INTO ROLES VALUES('Student',1, GETDATE(), GETDATE())
INSERT INTO ROLES VALUES('Admin',1, GETDATE(), GETDATE())


/****** Object:  Table [dbo].[COURSES]    Script Date: 8/25/2019 8:11:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].COURSES(
	[COURSE_ID] [int] IDENTITY NOT NULL,
	[COURSE_NAME] [varchar](200) NOT NULL,
	[ACTIVE_IND] [bit] NOT NULL,
	[CREATED_BY] [INT] NULL,
	[CREATED_DT] [datetime] NULL,
	[MODIFIED_DT] [datetime] NULL,
 CONSTRAINT [COURSE_ID_PK] PRIMARY KEY CLUSTERED 
(
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_ROLE_ID] UNIQUE NONCLUSTERED 
(
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


INSERT INTO COURSES VALUES('ASP.NET',1,1, GETDATE(), GETDATE())
INSERT INTO COURSES VALUES('ADO.NET',1,1, GETDATE(), GETDATE())
INSERT INTO COURSES VALUES('SQL',1,1, GETDATE(), GETDATE())
INSERT INTO COURSES VALUES('C#',1,1, GETDATE(), GETDATE())
INSERT INTO COURSES VALUES('MVC',1,1, GETDATE(), GETDATE())



/****** Object:  Table [dbo].[COURSE_TRAINER]    Script Date: 8/25/2019 8:11:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].COURSE_TRAINER(
	[CT_ID] [int] IDENTITY NOT NULL,
	[COURSE_ID] [int]  NOT NULL,
	[USER_ID] [int]  NOT NULL,
	[ACTIVE_IND] [bit] NOT NULL,
	[CREATED_BY] [INT] NULL,
	[CREATED_DT] [datetime] NULL,
	[MODIFIED_DT] [datetime] NULL,
 CONSTRAINT [COURSE_ID_PK] PRIMARY KEY CLUSTERED 
(
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]
ALTER TABLE COURSE_TRAINER
ADD CONSTRAINT FK_CourseUserID FOREIGN KEY ([USER_ID])
    REFERENCES USERS([USER_ID]);

ALTER TABLE [USER_ROLE_MAP]
ADD CONSTRAINT FK_CourseUID FOREIGN KEY ([COURSE_ID])
    REFERENCES COURSES([COURSE_ID]);
GO
GO

SET ANSI_PADDING OFF
GO



/****** Object:  Table [dbo].[USERS]    Script Date: 8/25/2019 8:31:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USERS](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [varchar](100) NOT NULL,
	[FIRST_NAME] [varchar](100) NULL,
	[MIDDLE_NAME] [varchar](100) NULL,
	[LAST_NAME] [varchar](100) NULL,
	[ACTIVE_IND] [bit] NULL,
	[EMAIL] [varchar](100) NULL,
	[PHONE_NO] [varchar](20) NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_BY] [int] NULL,
	[CREATED_DT] [datetime] NULL,
	[MODIFIED_DT] [datetime] NULL,
	
 CONSTRAINT [USERS_ID_PK] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_PATS_USER] UNIQUE NONCLUSTERED 
(
	[USER_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

INSERT INTO [USERS] VALUES('admin','admin',NULL, 'admin', 1,'admin@gmail.com','456454533',1,1,GETDATE(),GETDATE())





/****** Object:  Table [dbo].[USER_ROLE_MAP]    Script Date: 8/25/2019 8:36:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USER_ROLE_MAP](
	[USER_ROLE_MAP_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[ROLE_ID] [int] NULL,
	[ROLE_NAME] [varchar](200) NULL,
	[ACTIVE_IND] [bit] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_BY] [int] NULL,
	[CREATED_DT] [datetime] NULL,
	[MODIFIED_DT] [datetime] NULL,
 CONSTRAINT [USER_ROLE_MAP_ID_PK] PRIMARY KEY CLUSTERED 
(
	[USER_ROLE_MAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [USER_ROLE_MAP]
ADD CONSTRAINT FK_UserID FOREIGN KEY ([USER_ID])
    REFERENCES USERS([USER_ID]);

ALTER TABLE [USER_ROLE_MAP]
ADD CONSTRAINT FK_RoleId FOREIGN KEY ([ROLE_ID])
    REFERENCES ROLES([ROLE_ID]);
GO

SET ANSI_PADDING OFF
GO




/****** Object:  Table [dbo].[STUDENT_GRADES]    Script Date: 8/25/2019 8:36:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STUDENT_GRADES](
	[SG_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[COURSE_ID] [INT] NOT NULL,
	[GRADE] [varchar](50) NULL,
	[ACTIVE_IND] [bit] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_BY] [int] NULL,
	[CREATED_DT] [datetime] NULL,
	[MODIFIED_DT] [datetime] NULL,
 CONSTRAINT [SG_ID_PK] PRIMARY KEY CLUSTERED 
(
	[SG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [STUDENT_GRADES]
ADD CONSTRAINT FK_UserID1 FOREIGN KEY ([USER_ID])
    REFERENCES USERS([USER_ID]);

ALTER TABLE [STUDENT_GRADES]
ADD CONSTRAINT FK_USERID2 FOREIGN KEY ([CREATED_BY])
    REFERENCES USERS([USER_ID]);
GO

SET ANSI_PADDING OFF
GO





